### ISSUE TITLE
folder download

### ISSUE THREAD

**Issue by qwer0123456** [qwqdanchun/DcRat#10]
Folder download is not possible

Only one file is downloaded

Suggested download function of all files in selected folder

**Comment by qwqdanchun** [comment]
maybe just zip the folder and download it?

or download every file in the folder?

**Comment by qwer0123456** [comment]
Downloading after compression is not a good method

download every file in the folder best

**Comment by qwqdanchun** [comment]
download every file will creat many temp socket

may cause crash

**Comment by qwqdanchun** [comment]
or download one by one?
this is too slow

**Comment by qwqdanchun** [comment]
maybe can download ten by ten?

I still think zip and download is better

**Comment by qwer0123456** [comment]
If need one socket one file? bad.. ok

It seems like a better way to compress and transfer to temp folder path

The reason for suggesting this is

Downloading is inconvenient if there are many folders and files in the folder.

**Comment by qwqdanchun** [comment]
yes,I can't know what people will do when they use the rat.

So it's better to download the zip
