### ISSUE TITLE
Does this go to startup folder?

### ISSUE THREAD

**Issue by WildCD** [qwqdanchun/DcRat#16]
When a client shutsdown his computer i lose the client. Even when he turns the computer back on i don't see him anymore. Is this a bug or is it just not added?

**Comment by qwqdanchun** [comment]
do u choose the install option in builder or click schtask install after client connect



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 25, 2021 04:34 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/DcRat] Does this go to startup folder? (#16)




 
When a client shutsdown his computer i lose the client. Even when he turns the computer back on i don't see him anymore. Is this a bug or is it just not added?

**Comment by WildCD** [comment]
I use the install option. But i haven't used schtasks. Do i need to manually install schtasks when i get a new client?

**Comment by WildCD** [comment]
Nevermind got it working.

**Comment by qwqdanchun** [comment]
if u use install option,or install schtasks,both can make the client reconnect when the PC reboot

**Comment by WildCD** [comment]
Well it cannot find some file from appdata roaming when i press schtask install

**Comment by qwqdanchun** [comment]
what about the temp folder

**Comment by WildCD** [comment]
I have install in temp folder

**Comment by qwqdanchun** [comment]
maybe do not have access to appdata.so it install in temp

**Comment by WildCD** [comment]
It looks for C:\Users\"User"\AppData\Roaming\tmpDF2F.tmp.exe and i have the install function selected to temp and i tried to change it to appdata but i still get the same error.

**Comment by qwqdanchun** [comment]
check if you have the access to write to appdata folder

**Comment by WildCD** [comment]
Well my virtual machine has admin permissions. So i should have access.

**Comment by qwqdanchun** [comment]
so are u running the client in admin



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 26, 2021 18:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [qwqdanchun/DcRat] Does this go to startup folder? (#16)




 
Well my virtual machine has admin permissions. So i should have access.

**Comment by WildCD** [comment]
Yes

**Comment by qwqdanchun** [comment]
don't know why

**Comment by WildCD** [comment]
The fix was to install the version you uploaded 3 days ago. Thx.
