### ISSUE TITLE
DcRat latest build (non-release) | Password recovery fails to grab passwords

### ISSUE THREAD

**Issue by NotASkid2020** [qwqdanchun/DcRat#17]
**Describe the bug**
Password recovery fails on client

**To Reproduce**
Allow yourself to connect. Try to recover passwords
Elevate to admin, try to recover

**Expected behavior**
Passwords should be recovered

**Screenshots**
![image](https://user-images.githubusercontent.com/75049305/116238949-0fc88380-a730-11eb-8028-971702a6fd79.png)

**Desktop (please complete the following information):**
OS: WIndows 10
Program Version: Latest build (not release)

**Comment by NotASkid2020** [comment]
To add, I have passwords saved in Brave, chrome, and edge

**Comment by qwqdanchun** [comment]
try the https://github.com/qwqdanchun/DcRat/releases/tag/AutoBuild
or check the commit yeterday i push

**Comment by qwqdanchun** [comment]
Password recovery works not good on chrome v90.
I'll fix this in days

**Comment by NotASkid2020** [comment]
Alright. Also, another part of the issue was other chromium browsers arent supported. I know thats in the works though

**Comment by qwqdanchun** [comment]
will add more browser .
After fix the bug for v90

**Comment by NotASkid2020** [comment]
Alright, thank you
