### ISSUE TITLE
师傅您好，生成的client.exe的一些问题

### ISSUE THREAD

**Issue by 98Kstar** [qwqdanchun/DcRat#23]
师傅您好，我在使用公网vps时，回连地址为127.0.0.1时，在本机上是可以上线，但是使用我vps的公网地址在本机跟其他机器运行时无法上线，不知道是什么问题

**Comment by qwqdanchun** [comment]
服务器安全组是否允许端口连入



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 下午4:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/DcRat] 师傅您好，生成的client.exe的一些问题 (#23)




 
师傅您好，我在使用公网vps时，回连地址为127.0.0.1时，在本机上是可以上线，但是使用我vps的公网地址在本机跟其他机器运行时无法上线，不知道是什么问题

**Comment by 98Kstar** [comment]
是允许的，端口我是全部开放的。其他的如cs msf 过该端口都是可以的。

**Comment by qwqdanchun** [comment]
可以的话，将builder界面截图我看下？记得给ip打码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/DcRat] 师傅您好，生成的client.exe的一些问题 (#23)




 
是允许的，端口我是全部开放的。其他的如cs msf 过该端口都是可以的。

**Comment by 98Kstar** [comment]
哈哈，师傅不好意思，是我云端的端口没开，不好意思，打搅您了。
