### ISSUE TITLE
未能找到文件“xxx\Plugins\Miscellaneous.dll”

### ISSUE THREAD

**Issue by fishmisswater** [qwqdanchun/DcRat#36]
**Describe the bug**
某些功能，比如remote shell 会报这个错误

**Desktop**
 - OS: win 10

**Comment by qwqdanchun** [comment]
检查一下，是否文件被杀毒软件查杀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月16日(周五) 凌晨4:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/DcRat] 未能找到文件“xxx\Plugins\Miscellaneous.dll” (#36)




 
Describe the bug
 某些功能，比如remote shell 会报这个错误
 
Desktop (please complete the following information):
  
OS: win 10

**Comment by fishmisswater** [comment]
确实是杀软的原因，重新编译一下，在无杀软环境正常了
