### ISSUE TITLE
Keylogger offline ?

### ISSUE THREAD

**Issue by Dazmed707** [qwqdanchun/DcRat#4]
DcRat have the hability the keylogger offline ?

Password Recovery Not Found, Include Porject "HackBrowserData" in DcRat?

change translate "Procrss Manager" to "Process Manager"

**Comment by qwqdanchun** [comment]
offline keylogger is a good idea ,will add it tomorrow.
i use sharpchromium for password recovery,link is here  https://github.com/djhohnstein/SharpChromium
for the translation,i will change it tomorrow too

**Comment by Dazmed707** [comment]
can you include these projects as an option?

https://github.com/bitsadmin/fakelogonscreen

https://github.com/moonD4rk/HackBrowserData

https://github.com/djhohnstein/SharpChromium

**Comment by qwqdanchun** [comment]
fakelogonscreen is a good project,however it's not suitable for all the version,for example,win 7
HackBrowserData is written in go,so you'd better send it to disk and run from cmd
SharpChromium is already included before.

For the keylogger,I think it's a better way for you to send something like "https://github.com/NYAN-x-CAT/LimeLogger" to memory in the auto task,then Keylogger will run as soon as the client run.(cause i don't want to increase the size of client)

**Comment by Dazmed707** [comment]
quasar rat has a thin client with offline keylogger

There are also C language projects in github for offline FUD keyloggers and thin clients that could be included in the DcRat code.

**Comment by qwqdanchun** [comment]
Auto task is a good choose.
Quasar has a client for about 500k ,which is 10 times than DcRat.

**Comment by qwqdanchun** [comment]
Already add auto keylogger to auto task

**Comment by Dazmed707** [comment]
check these projects maybe they will help you to improve dcrat

https://github.com/LimerBoy?tab=repositories

**Comment by qwqdanchun** [comment]
seen these before,the chrome recovery has some error ,so i didn't choose

**Comment by Dazmed707** [comment]
i think it no longer supports current versions of chrome ..

**Comment by qwqdanchun** [comment]
cause there are so many browser ,i would just add chrome and edge recovery in my project

**Comment by Dazmed707** [comment]
FIREFOX IS ALSO VERY USED those 3 could be
with this project maybe

https://github.com/LimerBoy/FireFox-Thief

or can you create a FUD fork of HackBrowserData?

or add a killer antivirus?

**Comment by qwqdanchun** [comment]
Maybe create a new project about this in the future.
I won't creat fud for others.

**Comment by Dazmed707** [comment]
I can't find the offline keylogger option in 1.0.3

you can add AsyncRat Password Recovery. the one of that project if it is working

**Comment by Dazmed707** [comment]
would you like a new project starting here for android? make it fud

https://github.com/qH0sT/AndroSpy

**Comment by qwqdanchun** [comment]
find the auto keylogger in the auto tasks.

AsyncRat Password Recovery alert error sometimes ,not a good choice.

May create other projects in the futher ,however,not now.

**Comment by Dazmed707** [comment]
ok thanks.

**Comment by Dazmed707** [comment]
I can't find the offline keylogger
can you guide me a bit?

**Comment by qwqdanchun** [comment]
![image](https://user-images.githubusercontent.com/48477028/111804689-43cbb000-890b-11eb-8664-5159ca25c3c5.png)

**Comment by Dazmed707** [comment]
a ok-- thanks :)

**Comment by Dazmed707** [comment]
if i close dcrat
and I reconnect how do I extract the keylogger offline?

**Comment by qwqdanchun** [comment]
%appdata%\qwqdanchunLog.txt

**Comment by Dazmed707** [comment]
You could add in dcrat that option that extracts the txt and saves it in the client folder as keyloggeroffline

**Comment by Dazmed707** [comment]
not found with dcrat closed

**Comment by qwqdanchun** [comment]
will test it tomorrow
