### ISSUE TITLE
 Question about Get-ip site

### ISSUE THREAD

**Issue by Toxenskiy** [qwqdanchun/DcRat#40]
How does this feature work?

She gets the site's ip and tries to connect to it.
or
She gets the ip from the site, tries to connect and then gets the ip from the site again and tries to connect. 

P.S. 
How do you like the idea of adding a backup ip / site address?
How do you like the idea of adding a watchdog?

**Comment by qwqdanchun** [comment]
second one



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 20, 2021 23:21 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/DcRat]  Question about Get-ip site (#40)




 
How does this feature work?
 
She gets the site's ip and tries to connect to it.
 or
 She gets the ip from the site, tries to connect and then gets the ip from the site again and tries to connect.

**Comment by Toxenskiy** [comment]
How do you like the idea of adding a backup ip / site address?
How do you like the idea of adding a watchdog?

**Comment by qwqdanchun** [comment]
this is easy to add



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 21, 2021 00:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [qwqdanchun/DcRat]  Question about Get-ip site (#40)




 
How do you like the idea of adding a backup ip / site address?
 How do you like the idea of adding a watchdog?

**Comment by Toxenskiy** [comment]
ok
