### ISSUE TITLE
I hope the remote screen can play sound in real time

### ISSUE THREAD

**Issue by AllCheeks** [qwqdanchun/DcRat#42]
lf it can be achieved
thx

**Comment by qwqdanchun** [comment]
will add this in the future




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qwqdanchun/DcRat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 下午2:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qwqdanchun/DcRat] I hope the remote screen can play sound in real time (#42)





 
thx

**Comment by AllCheeks** [comment]
ojbk

**Comment by AllCheeks** [comment]
ojbk
