### ISSUE TITLE
遇到分辨率为 1536 x 864 的屏幕 远程桌面无法显示完全

### ISSUE THREAD

**Issue by AllCheeks** [qwqdanchun/DcRat#44]
遇到分辨率为 1536 x 864 的屏幕 远程桌面无法完整的显示屏幕
这是什么问题:O

**Comment by qwqdanchun** [comment]
试下直接生成的client，看下有没有这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 晚上6:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/DcRat] 遇到分辨率为 1536 x 864 的屏幕 远程桌面无法显示完全 (#44)




 
遇到分辨率为 1536 x 864 的屏幕 远程桌面无法显示完全
 这是什么问题:O

**Comment by AllCheeks** [comment]
懒 一般用不到大概 就不管他先了
