### ISSUE TITLE
Ransomware

### ISSUE THREAD

**Issue by leogotyou** [qwqdanchun/DcRat#49]
I testet this rat on a VM. I wanted to test the ransomware feature. The encrypting works Perfectly but the decrypting does not work. After I've Encrypted the Files I pressed on Decrypt on the rat panel. It said Password so i put in a password but when i tried to do put the password in the decrypter it said "Wrong Password"

pls tell me how tis works :)

**Comment by qwqdanchun** [comment]
you should find the password at client folder



---Original---
From: ***@***.***&gt;
Date: Sat, Aug 14, 2021 22:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/DcRat] Randomware (#49)




 
I testet this rat on a VM. I wanted to test the ransomware feature. The encrypting works Perfectly but the decrypting does not work. After I've Encrypted the Files I pressed on Decrypt on the rat panel. It said Password so i put in a password but when i tried to do put the password in the decrypter it said "Wrong Password"
 
pls tell me how tis works :)

**Comment by leogotyou** [comment]
thx
