### ISSUE TITLE
通过内网转发上线的机器不显示真实IP

### ISSUE THREAD

**Issue by Gofreedom0** [qwqdanchun/DcRat#52]
我通过内网转发工具（FRP）,把内网的8848端口映射到外网了，然后通过get ip by link或者外网ip上线，上线后的机器ip显示本地127.0.0.1:8848，不显示真实外网ip
![image](https://user-images.githubusercontent.com/22413346/130037690-8d07e753-42ea-4f6e-91cd-69a945d9f93f.png)

还有想问下那个生成exe时候的sleep功能，只是上线前sleep么还是使用所有功能前都会sleep

**Comment by qwqdanchun** [comment]
建议是直接用服务器使用，如果想使用内网穿透可以自己更改代码，改变获取ip的方式


另，sleep是运行之后睡眠一段时间，不会影响后面的执行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月19日(周四) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/DcRat] 通过内网转发上线的机器不显示真实IP (#52)




 
我通过内网转发工具（FRP）,把内网的8848端口映射到外网了，然后通过get ip by link或者外网ip上线，上线后的机器ip显示本地127.0.0.1:8848，不显示真实外网ip
 
 
还有想问下那个生成exe时候的sleep功能，只是上线前sleep么还是使用所有功能前都会sleep

**Comment by Gofreedom0** [comment]
非常感谢您的回复，由于我不会C#，所以暂时就这样用8（期待后续更新）
