### ISSUE TITLE
starting

### ISSUE THREAD

**Issue by GatoEatsAss** [qwqdanchun/DcRat#65]
tried the v1.07 built it and it didnt launch when i ran the exe had the same problem with the auto build any help would be appreciated

**Comment by GatoEatsAss** [comment]
i run the exe and nada happens

**Comment by GatoEatsAss** [comment]
even with the auto build

**Comment by qwqdanchun** [comment]
check your vs

this project can be easily built with vs2019 default config

or just use github action to build it

**Comment by GatoEatsAss** [comment]
worked in my VM wierd not on my main

**Comment by GatoEatsAss** [comment]
built it right when i run the exe nothing happens so strange
