### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Logwn** [qwqdanchun/DcRat#7]
in the auto tasks make an option on how they get triggered. 
Like if they get triggered on connect or if the user does something.
Add more auto tasks so like it will automatically bypass UAC and disable WD on connect.
Add upnp for the noobs out there.
process persistence would be nice
The ransomware doesnt work on my vm so maybe fix that.
You could make the chat look a bit better.
Add troll features and such.

**Comment by qwqdanchun** [comment]
will add some option in auto tasks, maybe contains "admin/user ,install/uninstall ,Group". if you have other suggest option, just tell me

will add disable UAC and disable WD to auto task. Bypass UAC is not suitable for all the antivirus,it will alert, so i haven't found a good way to make it auto bypass all the av.

upnp,maybe you mean reverse proxy? will add when i have free time.

what do you mean by process persistence,can't understand

ransomware works,but you should wait for it about several minutes

I really not good at UI, but i will try to change it.

won't add troll

**Comment by Logwn** [comment]
Upnp meaning universal plug and play like automatic port forwarding. (Reverse proxy would be cool to have)
process persistence meaning if the client process is killed in task manager then it will reopen itself.
The UI is just fine how it is but you can change it. I like it

**Comment by qwqdanchun** [comment]
make a little change for the chat ui
and already add disable uac and wd to auto task
Reverse proxy or upnp may add in the future
if you install with schtask ,the client will try to run every 5 minutes

**Comment by Logwn** [comment]
Nice
Thanks for the edits
