### ISSUE TITLE
dark mode ui

### ISSUE THREAD

**Issue by qwer0123456** [qwqdanchun/DcRat#9]
<img width="754" alt="ui" src="https://user-images.githubusercontent.com/80979849/114350076-ae3add80-9ba3-11eb-8270-d7604ad8979a.png">

White in dark windows is eye strain

It would be nice if there was a background color mode other than white

Dark mode is good Ui lol

##################################

<img width="409" alt="ui2" src="https://user-images.githubusercontent.com/80979849/114351052-0c1bf500-9ba5-11eb-83f5-27bb97c28af9.png">

top bar, ip port, country, time, logs

Some white and mouse menu background colors have also been modified

**Comment by qwqdanchun** [comment]
For I am not good at UI design.
I think i can't do this.😂
Maybe you can change it yourself.
